/**
 * Lean tool registry for the AI router system prompt.
 * Contains only metadata the AI needs — no icons, no React components.
 * Kept compact to minimize token usage in every API call.
 */

export interface RegistryTool {

  href: string;
  name: string;
  category: string;
  description: string;
  keywords: string[];
  command?: string;
}

export const agentToolRegistry: RegistryTool[] = [
  // ── Image Tools ──────────────────────────────────────────────
  {
    href: "/tools/bg-removal",
    command: "/backgroundremover",
    name: "Background Removal",
    category: "Image Tools",
    description: "Remove background from images instantly using AI. Supports PNG, JPG.",
    keywords: ["background", "remove bg", "transparent", "cutout", "erase background", "no bg"],
  },
  {
    href: "/tools/phone-mockups",
    command: "/phonemockups",
    name: "Phone Mockups",
    category: "Image Tools",
    description: "Place screenshots into iPhone/Android device frames.",
    keywords: ["mockup", "phone frame", "iphone", "android", "screenshot", "device frame"],
  },
  {
    href: "/tools/image-compression",
    command: "/imagecompressor",
    name: "Image Compression",
    category: "Image Tools",
    description: "Compress images to reduce file size while maintaining quality.",
    keywords: ["compress image", "reduce image size", "optimize image", "shrink image", "smaller image"],
  },
  {
    href: "/tools/image-converter",
    command: "/formatconverter",
    name: "Format Converter",
    category: "Image Tools",
    description: "Convert images between JPG, PNG, WebP, GIF, BMP, TIFF, SVG.",
    keywords: ["convert image", "jpg to png", "png to webp", "image format", "convert photo"],
  },
  {
    href: "/tools/color-correction",
    command: "/colorcorrection",
    name: "Color Correction",
    category: "Image Tools",
    description: "Adjust colors, brightness, contrast, saturation in images.",
    keywords: ["color correction", "brightness", "contrast", "saturation", "hue", "enhance photo", "filter"],
  },
  {
    href: "/tools/svg",
    command: "/svgtools",
    name: "SVG Tools",
    category: "Image Tools",
    description: "Edit SVG vector graphics, scale, modify colors, optimize paths.",
    keywords: ["svg", "vector", "svg editor", "svg optimize", "scale svg"],
  },
  {
    href: "/tools/color-converter",
    command: "/colorconverter",
    name: "Color Converter",
    category: "Image Tools",
    description: "Convert between HEX, RGB, HSL color formats with live preview.",
    keywords: ["color convert", "hex to rgb", "rgb to hsl", "color format", "hex code"],
  },
  {
    href: "/tools/image-resizer",
    command: "/imageresizer",
    name: "Image Resizer",
    category: "Design Tools",
    description: "Resize images to exact dimensions or by percentage. Lock aspect ratio.",
    keywords: ["resize image", "image dimensions", "scale image", "crop image", "make smaller", "1080x1080", "square"],
  },

  // ── File Tools ────────────────────────────────────────────────
  {
    href: "/tools/pdf",
    command: "/pdftools",
    name: "PDF Tools",
    category: "File Tools",
    description: "Merge, split, compress, and manipulate PDF files. Extract text, rotate pages, add watermarks.",
    keywords: ["pdf", "compress pdf", "merge pdf", "split pdf", "pdf tools", "pdf converter", "pdf compress", "reduce pdf size"],
  },
  {
    href: "/tools/zip",
    command: "/ziptools",
    name: "Zip Tools",
    category: "File Tools",
    description: "Create, extract, and manage ZIP archives. Compress files and folders.",
    keywords: ["zip", "unzip", "archive", "extract zip", "compress files", "zip folder"],
  },
  {
    href: "/tools/spreadsheet",
    command: "/csvviewer",
    name: "CSV/Excel Viewer",
    category: "File Tools",
    description: "View and edit CSV and Excel files in your browser.",
    keywords: ["csv", "excel", "spreadsheet", "xlsx", "open csv", "view excel"],
  },
  {
    href: "/tools/file-converter",
    command: "/fileconverter",
    name: "File Converter",
    category: "File Tools",
    description: "Convert files between different formats: documents, images, audio, video.",
    keywords: ["file converter", "convert file", "document convert", "format converter"],
  },

  // ── Media Tools ───────────────────────────────────────────────
  {
    href: "/tools/video",
    command: "/videoeditor",
    name: "Video Editor",
    category: "Media Tools",
    description: "Trim, convert, and edit video files. Cut clips, merge videos, adjust quality.",
    keywords: ["video editor", "trim video", "cut video", "convert video", "mp4", "avi", "video compress"],
  },
  {
    href: "/tools/audio",
    command: "/audioeditor",
    name: "Audio Editor",
    category: "Media Tools",
    description: "Edit and process audio files. Trim, merge, convert formats, adjust volume.",
    keywords: ["audio editor", "trim audio", "audio convert", "mp3", "wav", "audio cut", "audio tools"],
  },
  {
    href: "/tools/mic-camera",
    command: "/mictester",
    name: "Mic & Camera Tester",
    category: "Media Tools",
    description: "Check your camera preview and test microphone input levels.",
    keywords: ["mic test", "camera test", "microphone", "webcam", "audio test", "video test"],
  },
  {
    href: "/tools/screen-recorder",
    name: "Screen Recorder",
    category: "Design Tools",
    description: "Record your screen, window, or tab directly in the browser.",
    keywords: ["screen recorder", "record screen", "screen capture", "screen video", "record screen"],
  },

  // ── Text & Language Tools ─────────────────────────────────────
  {
    href: "/tools/text-case",
    command: "/textcaseconverter",
    name: "Text Case Converter",
    category: "Text & Language Tools",
    description: "Convert text to uppercase, lowercase, title case, camelCase, snake_case.",
    keywords: ["text case", "uppercase", "lowercase", "camelcase", "snake case", "title case"],
  },
  {
    href: "/tools/text-counter",
    command: "/textcounter",
    name: "Text Counter",
    category: "Text & Language Tools",
    description: "Count words, characters, lines in text. Analyze readability.",
    keywords: ["word count", "character count", "text counter", "count words", "word counter"],
  },
  {
    href: "/tools/code-format",
    command: "/codeformatter",
    name: "Code Formatter",
    category: "Text & Language Tools",
    description: "Format and beautify code with proper indentation. Supports JS, Python, HTML, CSS, JSON.",
    keywords: ["code format", "code beautify", "format code", "prettify", "indent code", "code style"],
  },
  {
    href: "/tools/lorem-ipsum",
    command: "/loremipsumgenerator",
    name: "Lorem Ipsum Generator",
    category: "Text & Language Tools",
    description: "Generate placeholder text for designs and mockups.",
    keywords: ["lorem ipsum", "placeholder text", "dummy text", "generate text", "filler text"],
  },
  {
    href: "/tools/typing-test",
    command: "/typingtest",
    name: "Typing Test",
    category: "Text & Language Tools",
    description: "Measure typing speed (WPM) and accuracy.",
    keywords: ["typing test", "typing speed", "wpm", "typing practice"],
  },
  {
    href: "/tools/text-diff",
    command: "/textdiffviewer",
    name: "Text Diff Viewer",
    category: "Text & Language Tools",
    description: "Compare two texts and see differences highlighted.",
    keywords: ["text diff", "compare text", "text comparison", "diff tool", "find differences"],
  },
  {
    href: "/tools/markdown-editor",
    command: "/markdowneditor",
    name: "Markdown Editor",
    category: "Text & Language Tools",
    description: "Write Markdown with live split-pane preview. Export as HTML.",
    keywords: ["markdown", "markdown editor", "md editor", "markdown preview"],
  },
  {
    href: "/tools/html-formatter",
    command: "/htmlformatter",
    name: "HTML Formatter",
    category: "Text & Language Tools",
    description: "Format, prettify, or minify HTML code.",
    keywords: ["html format", "html beautify", "html minify", "prettify html"],
  },
  {
    href: "/tools/notepad",
    command: "/notepad",
    name: "Notepad",
    category: "Text & Language Tools",
    description: "Distraction-free scratch pad that saves notes automatically.",
    keywords: ["notepad", "notes", "text editor", "write notes", "scratch pad"],
  },
  {
    href: "/tools/text-sorter",
    command: "/textsorter",
    name: "Text Sorter",
    category: "Text & Language Tools",
    description: "Sort lines alphabetically, by length, or numerically. Remove duplicates.",
    keywords: ["sort text", "sort lines", "alphabetical sort", "remove duplicates"],
  },
  {
    href: "/tools/morse-code",
    command: "/morsecodeconverter",
    name: "Morse Code Converter",
    category: "Text & Language Tools",
    description: "Convert text to Morse code and decode Morse code back to text.",
    keywords: ["morse code", "morse converter", "encode morse", "decode morse"],
  },
  {
    href: "/tools/word-frequency",
    command: "/wordfrequencyanalyzer",
    name: "Word Frequency Analyzer",
    category: "Text & Language Tools",
    description: "Analyze word frequency in text. Find most common words.",
    keywords: ["word frequency", "word analysis", "word count", "text analysis", "keyword frequency"],
  },
  {
    href: "/tools/markdown-html",
    command: "/markdowntohtml",
    name: "Markdown to HTML",
    category: "Text & Language Tools",
    description: "Convert Markdown to clean HTML.",
    keywords: ["markdown to html", "md to html", "convert markdown"],
  },
  {
    href: "/tools/text-repeater",
    command: "/textrepeater",
    name: "Text Repeater",
    category: "Text & Language Tools",
    description: "Repeat any text or character N times with a custom separator.",
    keywords: ["repeat text", "text repeat", "duplicate text"],
  },
  {
    href: "/tools/markdown-table",
    command: "/markdowntablegenerator",
    name: "Markdown Table Generator",
    category: "Text & Language Tools",
    description: "Build tables in a visual grid editor and export as Markdown.",
    keywords: ["markdown table", "table generator", "md table"],
  },
  {
    href: "/tools/rich-editor",
    command: "/richeditor",
    name: "Rich Editor",
    category: "Text & Language Tools",
    description: "Edit rich text with bold, italic, lists, links. Export to HTML or Markdown.",
    keywords: ["rich text editor", "wysiwyg", "text editor", "format text"],
  },

  // ── Data Tools ────────────────────────────────────────────────
  {
    href: "/tools/json-csv",
    command: "/jsontocsv",
    name: "JSON to CSV",
    category: "Data Tools",
    description: "Convert JSON data to CSV format for spreadsheet applications.",
    keywords: ["json to csv", "convert json", "json converter", "data convert"],
  },
  {
    href: "/tools/base64",
    command: "/base64tools",
    name: "Base64 Tools",
    category: "Data Tools",
    description: "Encode or decode Base64 strings and files.",
    keywords: ["base64", "encode base64", "decode base64", "base64 converter"],
  },
  {
    href: "/tools/qr-generator",
    command: "/qrgenerator",
    name: "QR Code Generator",
    category: "Data Tools",
    description: "Generate QR codes from text, URLs, contact information.",
    keywords: ["qr code", "qr generator", "generate qr", "create qr", "qr code maker"],
  },
  {
    href: "/tools/barcode-generator",
    command: "/barcodegenerator",
    name: "Barcode Generator",
    category: "Data Tools",
    description: "Generate barcodes including CODE128, EAN-13, UPC-A.",
    keywords: ["barcode", "barcode generator", "generate barcode", "ean barcode"],
  },
  {
    href: "/tools/qr-scanner",
    command: "/qrscanner",
    name: "QR Code Scanner",
    category: "Data Tools",
    description: "Scan QR codes using camera or upload image.",
    keywords: ["qr scanner", "scan qr", "read qr", "qr reader"],
  },
  {
    href: "/tools/barcode-scanner",
    command: "/barcodescanner",
    name: "Barcode Scanner",
    category: "Data Tools",
    description: "Scan barcodes using camera or upload image.",
    keywords: ["barcode scanner", "scan barcode", "read barcode"],
  },
  {
    href: "/tools/charts",
    command: "/charts",
    name: "Charts",
    category: "Data Tools",
    description: "Create beautiful charts: area, bar, line, pie, radar. Multiple export options.",
    keywords: ["chart", "graph", "data visualization", "bar chart", "pie chart", "line graph", "create chart"],
  },
  {
    href: "/tools/json-formatter",
    command: "/jsonformatter",
    name: "JSON Formatter",
    category: "Data Tools",
    description: "Format, validate, and minify JSON. Pretty-print with syntax highlighting.",
    keywords: ["json format", "json beautify", "format json", "validate json", "json viewer"],
  },
  {
    href: "/tools/yaml-json",
    command: "/yamltojson",
    name: "YAML ↔ JSON",
    category: "Data Tools",
    description: "Convert between YAML and JSON formats.",
    keywords: ["yaml to json", "json to yaml", "yaml converter", "yaml json"],
  },
  {
    href: "/tools/url-encoder",
    command: "/urlencoder",
    name: "URL Encoder/Decoder",
    category: "Data Tools",
    description: "Encode or decode URLs and query strings.",
    keywords: ["url encode", "url decode", "percent encode", "url converter"],
  },
  {
    href: "/tools/fake-data",
    command: "/fakedatagenerator",
    name: "Fake Data Generator",
    category: "Data Tools",
    description: "Generate realistic fake data: names, emails, addresses, credit cards.",
    keywords: ["fake data", "test data", "dummy data", "generate data", "mock data"],
  },
  {
    href: "/tools/text-binary",
    command: "/texttobinary",
    name: "Text to Binary",
    category: "Data Tools",
    description: "Convert text to binary, hexadecimal, octal representations.",
    keywords: ["text to binary", "binary converter", "hex converter", "binary decode"],
  },
  {
    href: "/tools/json-to-ts",
    command: "/jsontotypescript",
    name: "JSON → TypeScript",
    category: "Data Tools",
    description: "Paste JSON and get TypeScript interfaces instantly.",
    keywords: ["json to typescript", "json to types", "typescript interface", "ts types"],
  },
  {
    href: "/tools/mermaid",
    command: "/mermaidviewer",
    name: "Mermaid Diagram Viewer",
    category: "Data Tools",
    description: "Write Mermaid markdown and see diagrams rendered live.",
    keywords: ["mermaid", "diagram", "flowchart", "sequence diagram", "er diagram"],
  },

  // ── Math & Finance Tools ──────────────────────────────────────
  {
    href: "/tools/invoice",
    command: "/invoicegenerator",
    name: "Invoice Generator",
    category: "Math & Finance Tools",
    description: "Create professional invoices with PDF export. Tax calculations included.",
    keywords: ["invoice", "create invoice", "invoice generator", "bill", "receipt", "professional invoice"],
  },
  {
    href: "/tools/unit-converter",
    command: "/unitconverter",
    name: "Unit Converter",
    category: "Math & Finance Tools",
    description: "Convert between units: length, weight, temperature, area, volume.",
    keywords: ["unit converter", "convert units", "measurement converter", "kg to lbs", "celsius to fahrenheit"],
  },
  {
    href: "/tools/timezone-converter",
    command: "/timezoneconverter",
    name: "Time Zone Converter",
    category: "Math & Finance Tools",
    description: "Convert times between different time zones worldwide.",
    keywords: ["timezone", "time zone converter", "convert time", "utc", "world time"],
  },
  {
    href: "/tools/calculator",
    command: "/calculator",
    name: "Calculator",
    category: "Math & Finance Tools",
    description: "Advanced calculator with basic and scientific modes.",
    keywords: ["calculator", "math calculator", "scientific calculator", "calculate"],
  },
  {
    href: "/tools/age-calculator",
    command: "/agecalculator",
    name: "Age Calculator",
    category: "Math & Finance Tools",
    description: "Calculate exact age in years, months, and days.",
    keywords: ["age calculator", "calculate age", "date of birth", "birthday calculator"],
  },
  {
    href: "/tools/number-base-converter",
    command: "/numberbaseconverter",
    name: "Number Base Converter",
    category: "Math & Finance Tools",
    description: "Convert between binary, octal, decimal, and hexadecimal.",
    keywords: ["number base", "binary to decimal", "hex to decimal", "base converter"],
  },
  {
    href: "/tools/expense-tracker",
    command: "/expensetracker",
    name: "Expense Tracker",
    category: "Math & Finance Tools",
    description: "Track expenses with categories, budgets, and charts.",
    keywords: ["expense tracker", "budget", "track spending", "money tracker", "finance"],
  },
  {
    href: "/tools/currency-converter",
    command: "/currencyconverter",
    name: "Currency Converter",
    category: "Math & Finance Tools",
    description: "Convert between all major currencies using daily rates.",
    keywords: ["currency converter", "exchange rate", "convert currency", "usd to eur", "forex"],
  },
  {
    href: "/tools/loan-calculator",
    command: "/loancalculator",
    name: "Loan Calculator",
    category: "Math & Finance Tools",
    description: "Calculate monthly payments, total interest, amortization schedules.",
    keywords: ["loan calculator", "mortgage calculator", "emi calculator", "interest calculator"],
  },
  {
    href: "/tools/percentage-calculator",
    command: "/percentagecalculator",
    name: "Percentage Calculator",
    category: "Math & Finance Tools",
    description: "Calculate percentages, percentage change, reverse percentages.",
    keywords: ["percentage", "percent calculator", "calculate percentage", "percent change"],
  },
  {
    href: "/tools/aspect-ratio",
    command: "/aspectratiocalculator",
    name: "Aspect Ratio Calculator",
    category: "Math & Finance Tools",
    description: "Calculate and lock aspect ratios for images and videos.",
    keywords: ["aspect ratio", "16:9", "image ratio", "video ratio", "4:3"],
  },
  {
    href: "/tools/bmi-calculator",
    command: "/bmicalculator",
    name: "BMI Calculator",
    category: "Math & Finance Tools",
    description: "Calculate Body Mass Index (BMI) in metric or imperial units.",
    keywords: ["bmi", "body mass index", "bmi calculator", "weight health"],
  },
  {
    href: "/tools/tip-calculator",
    command: "/tipcalculator",
    name: "Tip Calculator",
    category: "Math & Finance Tools",
    description: "Calculate tips and split bills between multiple people.",
    keywords: ["tip calculator", "tip", "split bill", "bill splitter", "restaurant tip"],
  },

  // ── Productivity Tools ────────────────────────────────────────
  {
    href: "/tools/todo",
    command: "/todolist",
    name: "Todo List",
    category: "Productivity Tools",
    description: "Organize tasks and stay productive with priority levels.",
    keywords: ["todo", "task list", "to-do", "tasks", "checklist", "task manager"],
  },
  {
    href: "/tools/timer",
    command: "/timer",
    name: "Timer & Countdown",
    category: "Productivity Tools",
    description: "Simple timer and countdown with fullscreen mode.",
    keywords: ["timer", "countdown", "alarm", "countdown timer"],
  },
  {
    href: "/tools/pomodoro",
    command: "/pomodorotimer",
    name: "Pomodoro Timer",
    category: "Productivity Tools",
    description: "Boost focus with Pomodoro Technique. 25-min work sessions.",
    keywords: ["pomodoro", "focus timer", "work timer", "productivity timer"],
  },
  {
    href: "/tools/world-clock",
    command: "/worldclock",
    name: "World Clock",
    category: "Productivity Tools",
    description: "View current time in multiple cities and time zones.",
    keywords: ["world clock", "time zones", "city time", "global time"],
  },
  {
    href: "/tools/stopwatch",
    command: "/stopwatch",
    name: "Stopwatch",
    category: "Productivity Tools",
    description: "Precise stopwatch with lap times and split tracking.",
    keywords: ["stopwatch", "lap timer", "time tracking", "chronometer"],
  },
  {
    href: "/tools/habit-tracker",
    command: "/habittracker",
    name: "Habit Tracker",
    category: "Productivity Tools",
    description: "Track daily habits and build streaks.",
    keywords: ["habit tracker", "habits", "daily habits", "streak tracker"],
  },
  {
    href: "/tools/keep-awake",
    command: "/keepawake",
    name: "Keep Awake",
    category: "Productivity Tools",
    description: "Prevent laptop or phone from sleeping.",
    keywords: ["keep awake", "screen on", "prevent sleep", "wake lock"],
  },

  // ── Security & Development Tools ──────────────────────────────
  {
    href: "/tools/uuid-generator",
    command: "/uuidgenerator",
    name: "UUID Generator",
    category: "Security & Development Tools",
    description: "Generate UUIDs in different versions and formats.",
    keywords: ["uuid", "generate uuid", "unique id", "guid"],
  },
  {
    href: "/tools/jwt-decoder",
    command: "/jwtdecoder",
    name: "JWT Decoder",
    category: "Security & Development Tools",
    description: "Decode and validate JSON Web Tokens.",
    keywords: ["jwt", "decode jwt", "json web token", "jwt parser"],
  },
  {
    href: "/tools/password-generator",
    command: "/passwordgenerator",
    name: "Password Generator",
    category: "Security & Development Tools",
    description: "Generate secure passwords with custom options.",
    keywords: ["password generator", "generate password", "strong password", "secure password"],
  },
  {
    href: "/tools/hash-generator",
    command: "/hashgenerator",
    name: "Hash Generator",
    category: "Security & Development Tools",
    description: "Generate MD5, SHA-1, SHA-256, SHA-512 hashes from text.",
    keywords: ["hash", "md5", "sha256", "checksum", "hash generator"],
  },
  {
    href: "/tools/unix-timestamp",
    command: "/unixtimestamp",
    name: "Unix Timestamp Converter",
    category: "Security & Development Tools",
    description: "Convert epoch seconds/milliseconds to human date.",
    keywords: ["unix timestamp", "epoch", "timestamp converter", "unix time"],
  },
  {
    href: "/tools/regex-tester",
    command: "/regextester",
    name: "Regex Tester",
    category: "Security & Development Tools",
    description: "Test JavaScript regular expressions with live highlighting.",
    keywords: ["regex", "regular expression", "regex tester", "regex pattern"],
  },
  {
    href: "/tools/cron-parser",
    command: "/cronparser",
    name: "Cron Parser",
    category: "Security & Development Tools",
    description: "Explain cron expressions and list next runs.",
    keywords: ["cron", "cron expression", "cron parser", "cron schedule"],
  },
  {
    href: "/tools/password-strength",
    command: "/passwordstrength",
    name: "Password Strength",
    category: "Security & Development Tools",
    description: "Analyze password strength in real time.",
    keywords: ["password strength", "check password", "password security"],
  },
  {
    href: "/tools/text-encryption",
    command: "/textencryption",
    name: "Text Encryption",
    category: "Security & Development Tools",
    description: "Encrypt and decrypt text using AES-256-GCM in browser.",
    keywords: ["encrypt", "decrypt", "encryption", "aes", "secure text"],
  },
  {
    href: "/tools/http-status",
    command: "/httpstatuscodes",
    name: "HTTP Status Codes",
    category: "Security & Development Tools",
    description: "Quick reference for all HTTP status codes.",
    keywords: ["http status", "404", "200", "status code", "http codes"],
  },
  {
    href: "/tools/css-minifier",
    command: "/cssminifier",
    name: "CSS Minifier",
    category: "Security & Development Tools",
    description: "Minify or beautify CSS code.",
    keywords: ["css minify", "minify css", "css compress", "css beautify"],
  },
  {
    href: "/tools/sql-formatter",
    command: "/sqlformatter",
    name: "SQL Formatter",
    category: "Security & Development Tools",
    description: "Format and beautify SQL queries.",
    keywords: ["sql format", "sql beautify", "format sql", "sql formatter"],
  },
  {
    href: "/tools/chmod",
    command: "/chmodcalculator",
    name: "Chmod Calculator",
    category: "Security & Development Tools",
    description: "Calculate Unix file permissions visually.",
    keywords: ["chmod", "file permissions", "unix permissions", "rwx"],
  },
  {
    href: "/tools/meta-tags",
    command: "/metatagsgenerator",
    name: "Meta Tags Generator",
    category: "Security & Development Tools",
    description: "Generate HTML meta tags, Open Graph tags, Twitter Cards.",
    keywords: ["meta tags", "og tags", "open graph", "seo tags", "twitter card"],
  },

  // ── Design Tools ─────────────────────────────────────────────
  {
    href: "/tools/css-gradient",
    command: "/cssgradientgenerator",
    name: "CSS Gradient Generator",
    category: "Design Tools",
    description: "Create CSS gradients visually. Linear, radial, conic.",
    keywords: ["css gradient", "gradient generator", "linear gradient", "radial gradient"],
  },
  {
    href: "/tools/color-palette",
    command: "/colorpalettegenerator",
    name: "Color Palette Generator",
    category: "Design Tools",
    description: "Generate harmonious color palettes from a base color.",
    keywords: ["color palette", "color scheme", "color generator", "palette maker"],
  },
  {
    href: "/tools/contrast-checker",
    command: "/contrastchecker",
    name: "Color Contrast Checker",
    category: "Design Tools",
    description: "Check color contrast ratios for WCAG accessibility.",
    keywords: ["contrast checker", "wcag", "accessibility", "color contrast", "a11y"],
  },
  {
    href: "/tools/color-blindness",
    command: "/colorblindnesssimulator",
    name: "Color Blindness Simulator",
    category: "Design Tools",
    description: "Simulate how images look to people with color blindness.",
    keywords: ["color blindness", "deuteranopia", "protanopia", "accessibility"],
  },
  {
    href: "/tools/exif-viewer",
    command: "/exifviewer",
    name: "EXIF Viewer",
    category: "Design Tools",
    description: "View EXIF metadata from photos: camera, GPS, aperture.",
    keywords: ["exif", "photo metadata", "image metadata", "camera data", "gps photo"],
  },
  {
    href: "/tools/emoji-picker",
    command: "/emojipicker",
    name: "Emoji Picker",
    category: "Design Tools",
    description: "Browse and search all Unicode emojis. Click to copy.",
    keywords: ["emoji", "emoji picker", "emoji search", "copy emoji"],
  },
  {
    href: "/tools/css-shadow",
    command: "/cssshadowgenerator",
    name: "CSS Box Shadow Generator",
    category: "Design Tools",
    description: "Build CSS box shadows visually with sliders.",
    keywords: ["box shadow", "css shadow", "shadow generator", "drop shadow"],
  },
  {
    href: "/tools/svg-png",
    command: "/svgtopng",
    name: "SVG to PNG Converter",
    category: "Design Tools",
    description: "Convert SVG vector files to PNG raster images.",
    keywords: ["svg to png", "convert svg", "svg png", "vector to raster"],
  },

  // ── AI Tools ──────────────────────────────────────────────────
  {
    href: "/tools/token-counter",
    command: "/tokencounter",
    name: "Token Counter",
    category: "AI Tools",
    description: "Count tokens for any text across AI models: GPT-4o, Claude, Llama.",
    keywords: ["token counter", "count tokens", "ai tokens", "llm tokens"],
  },
  {
    href: "/tools/context-window",
    command: "/contextwindowcalculator",
    name: "Context Window Calculator",
    category: "AI Tools",
    description: "Calculate how much of a model's context window your text uses.",
    keywords: ["context window", "context length", "tokens remaining", "ai context"],
  },
  {
    href: "/tools/ai-cost-calculator",
    command: "/aicostcalculator",
    name: "AI Cost Calculator",
    category: "AI Tools",
    description: "Estimate AI API costs by token counts and model.",
    keywords: ["ai cost", "api cost", "llm cost", "gpt cost", "token cost"],
  },
  {
    href: "/tools/model-comparison",
    command: "/modelcomparison",
    name: "Model Comparison",
    category: "AI Tools",
    description: "Compare AI language models: context size, pricing, capabilities.",
    keywords: ["model comparison", "compare models", "ai models", "llm comparison"],
  },
  {
    href: "/tools/system-prompt-builder",
    command: "/systempromptbuilder",
    name: "System Prompt Builder",
    category: "AI Tools",
    description: "Build structured system prompts for AI models.",
    keywords: ["system prompt", "prompt builder", "ai prompt", "claude prompt"],
  },
  {
    href: "/tools/prompt-library",
    command: "/promptlibrary",
    name: "Prompt Library",
    category: "AI Tools",
    description: "Save and organize AI prompts locally.",
    keywords: ["prompt library", "save prompts", "prompt collection", "ai prompts"],
  },
  {
    href: "/tools/claude-md-generator",
    command: "/claudemdgenerator",
    name: "CLAUDE.md Generator",
    category: "AI Tools",
    description: "Generate CLAUDE.md files for projects.",
    keywords: ["claude.md", "ai rules", "project instructions", "claude instructions"],
  },
  {
    href: "/tools/ai-rules-generator",
    command: "/airulesgenerator",
    name: "AI Rules Generator",
    category: "AI Tools",
    description: "Generate .cursorrules, .windsurfrules, Copilot instruction files.",
    keywords: ["cursorrules", "ai rules", "copilot instructions", "windsurf rules"],
  },
  {
    href: "/tools/json-schema-builder",
    command: "/jsonschemabuilder",
    name: "JSON Schema Builder",
    category: "AI Tools",
    description: "Build JSON schemas for LLM tool calls and function calling.",
    keywords: ["json schema", "function calling", "tool schema", "openai tools"],
  },
  {
    href: "/tools/mcp-config",
    command: "/mcpconfiggenerator",
    name: "MCP Config Generator",
    category: "AI Tools",
    description: "Generate Model Context Protocol config files for Claude Desktop.",
    keywords: ["mcp", "model context protocol", "mcp config", "claude desktop"],
  },
  {
    href: "/tools/prompt-formatter",
    command: "/promptformatter",
    name: "Prompt Formatter",
    category: "AI Tools",
    description: "Convert prompts between ChatML, Llama 3, Claude XML, plain text.",
    keywords: ["prompt format", "chatml", "llama format", "prompt converter"],
  },
  {
    href: "/tools/skill-builder",
    command: "/skillbuilder",
    name: "Skill / Agent Builder",
    category: "AI Tools",
    description: "Scaffold AI agent skill files with guided form.",
    keywords: ["skill builder", "agent builder", "ai skill", "agent skill"],
  },
  {
    href: "/tools/ai-instruction-diff",
    command: "/aiinstructiondiff",
    name: "AI Instruction Diff",
    category: "AI Tools",
    description: "Compare two system prompts or AI instruction sets side by side.",
    keywords: ["prompt diff", "instruction diff", "compare prompts", "ai diff"],
  },
  {
    href: "/tools/text-similarity",
    command: "/textsimilarity",
    name: "Text Similarity",
    category: "AI Tools",
    description: "Measure semantic similarity between texts using TF-IDF cosine similarity.",
    keywords: ["text similarity", "semantic similarity", "compare text", "cosine similarity"],
  },
  {
    href: "/tools/compress-video",
    command: "/videocompressor",
    name: "Video Compressor",
    category: "Media Tools",
    description: "Compress video files to reduce size while maintaining quality.",
    keywords: ["compress video", "reduce video size", "mp4 compress", "smaller video", "ffmpeg"],
  },
  {
    href: "/tools/youtube-downloader",
    command: "/youtubedownloader",
    name: "YouTube Downloader",
    category: "Media & Downloader Tools",
    description: "Download YouTube videos and audio tracks for free.",
    keywords: ["youtube downloader", "download youtube video", "youtube mp3", "youtube mp4", "yt download"],
  },
  {
    href: "/tools/tiktok-downloader",
    command: "/tiktokdownloader",
    name: "TikTok Downloader",
    category: "Media & Downloader Tools",
    description: "Download TikTok videos without watermark in high quality.",
    keywords: ["tiktok downloader", "download tiktok", "tiktok no watermark", "save tiktok"],
  },
  {
    href: "/tools/instagram-downloader",
    command: "/instagramdownloader",
    name: "Instagram Downloader",
    category: "Media & Downloader Tools",
    description: "Download Instagram Reels, videos, and stories from public accounts.",
    keywords: ["instagram downloader", "download instagram reel", "instagram story downloader", "ig download"],
  },
  {
    href: "/tools/twitter-downloader",
    command: "/twitterdownloader",
    name: "Twitter / X Downloader",
    category: "Media & Downloader Tools",
    description: "Download videos from Twitter (X) tweets.",
    keywords: ["twitter downloader", "x downloader", "download twitter video", "x video download"],
  },
  {
    href: "/tools/reddit-downloader",
    command: "/redditdownloader",
    name: "Reddit Downloader",
    category: "Media & Downloader Tools",
    description: "Download Reddit videos and GIFs from public posts.",
    keywords: ["reddit downloader", "download reddit video", "reddit mp4", "save reddit video"],
  },
  {
    href: "/tools/soundcloud-downloader",
    command: "/soundclouddownloader",
    name: "SoundCloud Downloader",
    category: "Media & Downloader Tools",
    description: "Download SoundCloud tracks as MP3 audio files.",
    keywords: ["soundcloud downloader", "soundcloud to mp3", "download soundcloud track"],
  },
  {
    href: "/tools/video-downloader",
    command: "/universaldownloader",
    name: "Universal Downloader",
    category: "Media & Downloader Tools",
    description: "All-in-one media downloader supporting YouTube, TikTok, Instagram, Twitter, Reddit, SoundCloud.",
    keywords: ["video downloader", "download video", "universal downloader", "media downloader", "cobalt"],
  },
  {
    href: "/tools/hls-downloader",
    command: "/hlsdownloader",
    name: "HLS Stream Downloader",
    category: "Media & Downloader Tools",
    description: "Download HLS (.m3u8) video streams and merge segments into a single MP4 file.",
    keywords: ["hls downloader", "m3u8 downloader", "download hls stream", "m3u8 to mp4", "stream downloader"],
  },
  {
    href: "/tools/youtube-thumbnail",
    command: "/youtubethumbnailgrabber",
    name: "YouTube Thumbnail Grabber",
    category: "Media & Downloader Tools",
    description: "Fetch and download YouTube video thumbnails in all available sizes.",
    keywords: ["youtube thumbnail", "download thumbnail", "yt thumbnail grabber", "save youtube cover"],
  },
  {
    href: "/tools/video-frame-extractor",
    command: "/videoframeextractor",
    name: "Video Frame Extractor",
    category: "Media & Downloader Tools",
    description: "Extract individual frames from any video file and save them as images locally.",
    keywords: ["frame extractor", "video frame", "capture frame", "extract image from video", "screenshot video"],
  },
];

/**
 * Returns a compact JSON string of the tool registry for use in AI system prompts.
 * Omits keywords to save tokens — the AI reads name + description.
 */
export function getToolRegistryForPrompt(): string {
  const compact = agentToolRegistry.map(({ href, name, category, description, command }) => ({
    href,
    name,
    category,
    description,
    command,
  }));
  return JSON.stringify(compact);
}
